_target_: src.loss.MatchingLoss
_recursive_: True
matcher:
  _target_: src.loss.HungarianMatcher
  class_cost: 1.
  params_cost: 2.
hits_generator:
  _target_: src.postprocess.EventRecoveryFromPredictions
  event_generator:
    _target_: src.data_generation.SPDEventGenerator
    max_event_tracks: ${dataset.max_event_tracks}
    detector_eff: ${dataset.detector_efficiency}
  track_params_normalizer: ${dataset.track_params_normalizer}
num_classes: 1
eos_coef: 0.2
losses: ["labels", "params"] #, "hits"
charge_as_class: False
weights_dict:
  loss_ce: 0.5
  loss_params: 1.0
  loss_hits: 0.0