train_samples: 64
val_samples: 32
max_event_tracks: 10
detector_efficiency: 1.0
truncation_length: 512
shuffle: False
hits_normalizer:
  _target_: src.normalization.ConstraintsNormalizer
track_params_normalizer:
  _target_: src.normalization.TrackParamsNormalizer
