defaults:
  - _self_
  - model: with_coords
  - criterion: with_coords
  - user_settings: user_settings
  - dataset: base

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_root}
results_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}
  sweep:
    dir: ${hydra_dir}/multirun
    subdir: ${hydra.job.num}


num_epochs: 40
batch_size: 32
random_seed: 13
logging_dir: ${hydra_dir}
resume_from_checkpoint: # E:\projects\trt\results\hydra\2024-11-17\23-58-59\checkpoint_epoch_39_val.pth
#r"D:\projects\trt\results\hydra\2024-05-13\15-12-40\TRT\version_0\epoch=265-step=266.ckpt"
num_workers: 1
pin_memory: False
freeze_model: False

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0001
  weight_decay: 0.0001  # 00001