defaults:
  - _self_
  - model: base
  - criterion: naive
  - user_settings: user_settings
  - dataset: base

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_root}
results_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}
  sweep:
    dir: ${hydra_dir}/multirun
    subdir: ${hydra.job.num}


num_epochs: 20000
train_batch_size: 32
val_batch_size: 32
random_seed: 42
logging_dir: ${hydra_dir}
resume_from_checkpoint: #r"D:\projects\trt\results\hydra\2024-05-13\15-12-40\TRT\version_0\epoch=265-step=266.ckpt"
num_workers: 0
pin_memory: False

metrics:
# TODO: rewrite metrics to more useful ones
  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher: ${criterion.matcher}
    hits_generator: ${criterion.hits_generator}
    num_classes: ${criterion.num_classes}
    eos_coef: ${criterion.eos_coef}
    losses: ["labels"]
    weights_dict: ${criterion.weights_dict}

  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher: ${criterion.matcher}
    hits_generator: ${criterion.hits_generator}
    num_classes: ${criterion.num_classes}
    eos_coef: ${criterion.eos_coef}
    losses: [ "params" ]
    weights_dict: ${criterion.weights_dict}

  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher: ${criterion.matcher}
    hits_generator: ${criterion.hits_generator}
    num_classes: ${criterion.num_classes}
    eos_coef: ${criterion.eos_coef}
    losses: [ "hits" ]
    weights_dict: ${criterion.weights_dict}

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.0  # 00001