defaults:
  - _self_
  - model: base
  - criterion: naive
  - user_settings: user_settings
  - dataset: base

project_path: ${user_settings.project_path}
datasets_root: ${user_settings.datasets_root}
results_dir: ${user_settings.hydra_dir}
hydra_root: ${user_settings.hydra_root}
hydra_dir: ${user_settings.hydra_dir}
hydra:
  run:
    dir: ${hydra_dir}
  sweep:
    dir: ${hydra_dir}/multirun
    subdir: ${hydra.job.num}


num_epochs: 20
train_batch_size: 16
val_batch_size: 16
random_seed: 42
logging_dir: ${hydra_dir}
resume_from_checkpoint: None
num_workers: 4
pin_memory: False

metrics:
# TODO: rewrite metrics to more useful ones
  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher:
      _target_: src.loss.HungarianMatcher
      class_cost: 1.
      params_cost: 1.
    hits_generator:
      _target_: src.postprocess.EventRecoveryFromPredictions
      event_generator:
        _target_: src.data_generation.SPDEventGenerator
        max_event_tracks: ${dataset.max_event_tracks}
        detector_eff: ${dataset.detector_efficiency}
      track_params_normalizer: ${dataset.track_params_normalizer}

    num_classes: 1
    eos_coef: 0.2
    losses: ["labels"]

  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher:
      _target_: src.loss.HungarianMatcher
      class_cost: 1.
      params_cost: 1.
    hits_generator:
      _target_: src.postprocess.EventRecoveryFromPredictions
      event_generator:
        _target_: src.data_generation.SPDEventGenerator
        max_event_tracks: ${dataset.max_event_tracks}
        detector_eff: ${dataset.detector_efficiency}
      track_params_normalizer: ${dataset.track_params_normalizer}
    num_classes: 1
    eos_coef: 0.2
    losses: [ "params" ]

  - _target_: src.loss.MatchingLoss
    _recursive_: True
    matcher:
      _target_: src.loss.HungarianMatcher
      class_cost: 1.
      params_cost: 1.
    hits_generator:
      _target_: src.postprocess.EventRecoveryFromPredictions
      event_generator:
        _target_: src.data_generation.SPDEventGenerator
        max_event_tracks: ${dataset.max_event_tracks}
        detector_eff: ${dataset.detector_efficiency}
      track_params_normalizer: ${dataset.track_params_normalizer}
    num_classes: 1
    eos_coef: 0.2
    losses: [ "hits" ]

optimizer:
  _target_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.0  # 00001